name: Verify Changelog.md update

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "confirm"
  confirm-changelog-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: Verify that the PR contains an update to changelog.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            changelog.md
          
      - name: Fail if no change to changelog.md
        if: steps.changed-files.outputs.any_changed != 'true'
        run: exit 1
